### ISSUE TITLE
Integrate Bearby wallet in wallet provider

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/wallet-provider#90]
Today wallet provider only works with wallet that use the massa wallet standard.
We need to add the possibility to use bearby with the wallet provider.
To do that, we need to provide an interface to connect to the bearby api

Tasks:
- check how to connect to bearby wallet
- add an "adapter" to use bearby wallet with the same interface so we can plug it to web3 like massaStation

**Comment by Elli610** [comment]
TODO:

Priority:
- [ ] see if bearby can allow us to broadcast tx through their wallet. Otherwise we'll have to hardcode a nodeUrl and won't be able to switch between buildnet and testnet without rebuilding the package
- [ ] check why the 'Transaction' objects we setup fail this assertion: https://github.com/bearby-wallet/bearby-web3/blob/32bb2f7688f01253d4d40eea73aed5077bab62b2/packages/wallet/wallet.ts#L195
- [ ] find a way to get all the arguments in a Args object to use them with bearby call function
- adapt all functions related to the non persistent execution

non urgent:
- [ ] test buy and sell rolls function
- [ ] test sendTransaction
- [ ] test callSC
- [ ] test balance
